const black = [
  'Resolução da ANAC agora proíbe ______ em aeronaves.',
  'É uma pena que as crianças hoje em dia estejam todas envolvidas em ______.',
  'Em 1000 anos, quando o dinheiro de papel for apenas uma lembrança distante, ______ será a nossa moeda.',
  'CPF proíbe ______ por proporcionar vantagem desleal aos jogadores.',
  'Qual o prazer proibído do Batman?',
  'Vem aí o novo livro de J.K. Rowling: Harry Potter e a Câmara de ______.',
  'Desculpe professora, mas é que eu não pude terminar o dever de casa por causa de ______.',
  'O que eu trouxe do Paraguai?',
  '______? Tem um app pra isso.',
  '______. Aposto que um só não te satisfaz!',
  'Qual é meu anti-droga?',
  'Enquanto os Estados Unidos e a União Soviética competiam na corrida espacial, o governo brasileiro investia pesado em ______.',
  'No novo filme da Disney, Hanna Montana enfrenta ______ pela primeira vez.',
  'Qual o meu poder secreto.',
  'Qual a dieta do momento.',
  'O que o Vin Diesel teve no jantar.',
  'Quando o faraó permaneceu imóvel, Moisés invocou dos céus a praga do ______.',
  'Como estou mantendo minha atual relação amorosa.',
  'Qual é o cúmulo da porquice?',
  'Dizem que em Bangu 3 se troca dez maços de cigarro por ______.',
  'Depois do terremoto, o Sean Penn levou ______ ao Haíti.',
  'No proximo natal o Papai Noel vai dar ______ pra criança que não se comportar.',
  'A vida dos índios americanos mudou para sempre quando o homem branco lhes apresendou ______.',
  'O que o Ministério da Educação está usando para inspirar os estudantes do interior a serem bem sucedidos',
  'Talvez ela tenha nascido assim. Talvez seja ______.',
  'Em seus momentos finais Michael Jackson pensou em ______.',
  'Homem branco gosta de ______.',
  'Porque eu estou todo doído?',
  'Um jantar romântico à luz de velas seria imcompleto sem ______.',
  'O que eu levaria ao passado para convencer as pessoas de que sou um mágico poderoso.',
  'Em breve, numa livraria perto de você, ______.',
  'A excursão escolar foi um fiasco devido a ______.',
  'Qual o melhor amigo de uma garota?',
  'Doutor Drauzio, estou tendo problemas com ______ e gostaria de ouvir seu conselho.',
  'Quando eu for precisante criarei o Departamento de ______.',
  'O que meus pais estão escondendo de mim?',
  'O que nunca falha em deixar uma festa mais animada?',
  'O que é que fica melhor quando envelhece?',
  '______: bom até a última gota.',
  'Estou com 99 problema, mas ______ não é um deles.',
  '______. É uma armadilha.',
  'Novo reality-show da MTV apresenta outo celebridades desgastadas morando com ______.',
  'O que é que a vovó acharia perturbante, mas estranhamente charmoso?',
  'O que é mais EMO?',
  'Durante o sexo, gosto de pensar em ______.',
  'O que causou o fim da minha última relação.',
  'Que som é esse?',
  '______. É assim que eu espero morrer.',
  'Porque minha pele está pegajosa?',
  'Qual é o próximo brinde do McLanche Feliz?',
  'O que é que tem à vontade no Céu?',
  'Não sei com que armas se lutará a terceira guerra mundial, mas a quarta será com ______.',
  'O que é tiro-e-queda para se conseguir sexo?',
  '______: testado pelas crianças, aprovado pelas mães.',
  'Por que não consigo dormir a noite.',
  'Que cheiro é esse?',
  'O que ajuda o Obama a relaxar depois do trabalho.',
  'Assim expira o mundo / Assim expira mundo / Não com uma explosão, mas com ______.',
  'Chega à Broadway nessa temporada o musical ______.',
  'Antropólogis recentemente descobriram uma tribo primitíva que cultua ______.',
  'Mas, antes de matá-lo, Sr. Bond, preciso te mostrar ______.',
  'Estudo mostra que ratos de laboratório atravessam labirintos 50% mais rápido depois de serem expostos à ______.',
  'Qual é a proxima dupla super-herói e ajudante.',
  'A seguir, na ESPN2: Campeonato Mundial de ______.',
  'Quando eu for bilionário, mandarei fazer uma estátua de 15 metros de altura para celebrar ______.',
  'Buscando aumentar sua audiência, o Musei de História natural abriu uma exposição interativa sobre ______.',
  'Guerra! Pra que serve?',
  'O que me causa gases incontroláveis.',
  'Idosos tem cheiro de que?',
  'O que vou deixar de fazer na quaresma?',
  'A medicina alternativa agora está explorando os poderes curativos de ______.',
  'O que os Estados Unidos jogaram, de avião, às crianças do Afeganistão?',
  'O que o Dick Cheney prefere?',
  'Historiadores encontram dezenas de cadernos de Picasso com esboços de ______.',
  'O que você espera não achar em seu prato de comida chinesa?',
  'Bebo para esquecer ______.',
  '______. Tô dentro!',
  '______. As mina pira, véi.',
  '______. Véi, na boa...',
  'E o prêmio ______ vai para ______',
  'E para meu próximo número, tirarei ______ de ______.',
  'Passo 1: ______. Passo 2: ______. Passo 3: Lucrar.',
  'Quando eu estava viajando no LCD, ______ se transformou em ______.',
  '______ é uma ladeira escorregadia que leva direto para ______.',
  'Em um mundo devastado por ______. nosso único consolo é ______.',
  'No próximo Tropa de Elite, Capitão Nascimento descobre que milicianos estavam usando ______ para ______.',
  'Nunca de fato entendi ______, até encontrar ______.',
  'Dizem as más linguas que o prato predileto do Vladimir Putim é ______ recheado com ______.',
  'Globo Filmes apresenta ______, a história de ______.',
  'Sim, eu matei ______. Como? ______.',
  '______ + ______ = ______.',
  'Faça um poema com três versos.',
];

export default black;
